### ISSUE TITLE
Question: CNI plugin or implementation of CNI as a spec?

### ISSUE THREAD

**Issue by leecalcote** [cloudfoundry-incubator/guardian-cni-adapter#1]
Hi,

Is the guardian-cni-adapter a CNI plugin (a network driver) or is it a complete implementation of CNI (as a specification)?

**Comment by rosenhouse** [comment]
Sorry if the README is confusing, CloudFoundry container networking is under active development and the documentation is lagging.

To answer your question: Guardian-CNI-adapter is not a CNI plugin.  When executed with the correct args, it will call one or more configured CNI plugins.  So in the language of the [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#general-considerations) it is a "container runtime".

Why do you ask?

**Comment by leecalcote** [comment]
Thanks, Gabe. That's helps. I understand now.

I'm doing a bit of analysis/writing on the subject and wanted to ensure I'm representing this efforts intentions accurately. DM me - @lcalcote on Twitter and I'll expound, if interested.

**Comment by rosenhouse** [comment]
Great.

FWIW, you can find the bulk of the CloudFoundry container networking code in the [netman](https://github.com/cloudfoundry-incubator/netman-release) repo.  That includes a vendored copy of this code, along with the higher-level integrations with the container runtime (Garden-RunC) and the user-facing parts of the CloudFoundry system.

I should probably update the CNI README to point there instead of here...
